import Head from "next/head";
import Image from "next/image";
import { Header } from "../components/Header";

const Home = () => {
	return (
		<>
			<Head>
				<title>One/24</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main className="mx-[10vw]">
				<Header />
        <div className="w-3/4 mx-auto">
          <div className="relative mx-auto h-[500px] border flex items-center justify-center">
            placeholder spash video
            {/* <Image alt="splash video placeholder" src="/images/home-1.jpeg" fill /> */}
          </div>
          <div>
            placeholder for 3 images
          </div>
        </div>
			</main>
		</>
	);
};

export default Home;
