import Head from 'next/head';
import React from 'react'
import { ArtistColumn } from '../components/ArtistColumn';
import { Header } from '../components/Header';
import { Video } from '../components/Video';
import { data } from '../data';

const Music = () => {
	return (
		<>
			<Head>
				<title>One/24 - Music</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main className="w-2/3 mx-auto">
				<Header />
				<div>
					<div className='text-xl italic flex justify-center mb-10'>
						The vibrations of music align with our own frequencies and create visceral connections with the world and with others.
					</div>
					<Video />
					<div className='grid grid-cols-4 mt-10'>
						<ArtistColumn title="Forgotten Classics" artists={data.music.forgottenClassics} />
						<ArtistColumn title="Overlooked Gems" artists={data.music.overlookedGems} />
						<ArtistColumn title="Emerging Artists" artists={data.music.emergingArtists} />
						<div className='border p-4'>
							Featured Artist, notes from editors, etc...
						</div>
					</div>
				</div>
			</main>
		</>
	);
}

export default Music;