import Head from 'next/head'
import { useRouter } from 'next/router';
import React from 'react'

const captializeFirstLetter = (s: string) => {
	return s.charAt(0).toUpperCase() + s.slice(1);
}

export const CustomHead = () => {
	const router = useRouter();
	const path = router.pathname;
	const title = path === '/' ? 'One/24' : `One/24 - ${captializeFirstLetter(path.slice(1))}`;

	return (
		<Head>
			<title>{title}</title>
			<meta name="description" content="Generated by create next app" />
			<meta name="viewport" content="width=device-width, initial-scale=1" />
			<link rel="icon" href="/favicon.ico" />
		</Head>
	);
}
